#!/bin/bash
echo "
─█▀▀█ ░█▀▀▀█ ─█▀▀█ ░█▀▀█ 
░█▄▄█ ─▀▀▀▄▄ ░█▄▄█ ░█▄▄█ 
░█─░█ ░█▄▄▄█ ░█─░█ ░█───
"
if [ "$#" -eq 0 ]; then
    echo "Speed up your local builds."
    echo "Prepend 'asap' to maven commands to get useless checks to be skipped while you're developing locally."
    echo "$(tput setaf 2)asap mvn clean install$(tput setaf 4)"
    exit 1
fi

pulsar_flags="-DskipSourceReleaseAssembly"
flags="-Dcheckstyle.skip -Dspotbugs.skip -Dlicense.skip -Drat.skip -Djavadoc.skip -Dmaven.javadoc.skip -nsu $pulsar_flags"

if [ "$1" == "mod" ]; then
    shift 
    mvnmod="install $flags -am -DskipTests -pl"
    if command -v mvnd &> /dev/null; then
        mvnd $mvnmod "$@"
    else
        mvn $mvnmod "$@"
    fi
elif [ "$1" == "cmod" ]; then
    shift 
    mvnmod="clean install $flags -am -DskipTests -pl"
    if command -v mvnd &> /dev/null; then
        mvnd $mvnmod "$@"
    else
        mvn $mvnmod "$@"
    fi
elif [ "$1" == "cmodonly" ]; then
    shift 
    mvnmod="clean install $flags -DskipTests -pl"
    if command -v mvnd &> /dev/null; then
        mvnd $mvnmod "$@"
    else
        mvn $mvnmod "$@"
    fi
elif [ "$1" == "modonly" ]; then
    shift 
    mvnmod="install $flags -DskipTests -pl"
    if command -v mvnd &> /dev/null; then
        mvnd $mvnmod "$@"
    else
        mvn $mvnmod "$@"
    fi
elif [ "$1" == "dep" ]; then
    shift 
    mvndep="dependency:tree $flags -pl $1"
    shift
    if command -v mvnd &> /dev/null; then
        mvnd $mvndep "$@" | less
    else
        mvn $mvndep "$@" | less
    fi
elif [ "$1" == "test" ]; then
    shift 
    mvnmod="test $flags -pl $1 -Dtest=$2"
    shift
    shift
    if command -v mvnd &> /dev/null; then
        mvnd $mvnmod "$@"
    else
        mvn $mvnmod "$@"
    fi
else
    "$@" $flags
fi
