#!/bin/bash
echo "
─█▀▀█ ░█▀▀▀█ ─█▀▀█ ░█▀▀█ 
░█▄▄█ ─▀▀▀▄▄ ░█▄▄█ ░█▄▄█ 
░█─░█ ░█▄▄▄█ ░█─░█ ░█───
"
if [ "$#" -eq 0 ]; then
    echo "Speed up your local builds."
    echo "Prepend 'asap' to maven commands to get useless checks to be skipped while you're developing locally."
    echo "$(tput setaf 2)asap mvn clean install$(tput setaf 4)"
    exit 1
fi

pulsar_flags="-DskipSourceReleaseAssembly"
flags="-Dcheckstyle.skip -Dspotbugs.skip -Dlicense.skip -Drat.skip -Djavadoc.skip -Dmaven.javadoc.skip -Dspotless.skip -nsu $pulsar_flags"

get_module_param() {
    local param=$1
    if [ "$1" != "." ]; then
        echo "-pl $param"
    fi
}

if [ "$1" == "mod" ]; then
    shift
    module=$(get_module_param $1)
    shift
    mvnmod="install $flags -am -DskipTests $module"
    if command -v mvnd &> /dev/null; then
        mvnd $mvnmod "$@"
    else
        mvn $mvnmod "$@"
    fi
elif [ "$1" == "cmod" ]; then
    shift
    module=$(get_module_param $1)
    shift
    mvnmod="clean install $flags -am -DskipTests $module"
    if command -v mvnd &> /dev/null; then
        mvnd $mvnmod "$@"
    else
        mvn $mvnmod "$@"
    fi
elif [ "$1" == "cmodonly" ]; then
    shift 
    module=$(get_module_param $1)
    shift
    mvnmod="clean install $flags -DskipTests $module"
    if command -v mvnd &> /dev/null; then
        mvnd $mvnmod "$@"
    else
        mvn $mvnmod "$@"
    fi
elif [ "$1" == "modonly" ]; then
    shift 
    module=$(get_module_param $1)
    shift
    mvnmod="install $flags -DskipTests $module"
    if command -v mvnd &> /dev/null; then
        mvnd $mvnmod "$@"
    else
        mvn $mvnmod "$@"
    fi
elif [ "$1" == "dep" ]; then
    shift 
    module=$(get_module_param $1)
    shift 
    mvndep="dependency:tree $flags $module"
    if command -v mvnd &> /dev/null; then
        mvnd $mvndep "$@" | less
    else
        mvn $mvndep "$@" | less
    fi
elif [ "$1" == "test" ]; then
    shift 
    module=$(get_module_param $1)
    shift
    mvnmod="test $flags $module -Dtest=$1"
    shift
    if command -v mvnd &> /dev/null; then
        mvnd $mvnmod "$@"
    else
        mvn $mvnmod "$@"
    fi
else
    "$@" $flags
fi
